# Site settings
title: Buckdecoder
email: donovanroseboom@yahoo.com
description: > # this means to ignore newlines until "baseurl:"
  Buckdecoder
  Machine Learning-based Hunting Software.
baseurl: ""
url: https://buckdecoder.github.io
github_username:  buckdecoder

# Build settings
markdown: kramdown
exclude: [README.md]
keep_files: [images assets]